//
//  ViewController.swift
//  GitIgnore
//
//  Created by Joshua Barrow on 1/27/15.
//  Copyright (c) 2015 Jukaela Enterprises. All rights reserved.
//

import Cocoa

class ViewController: NSViewController {

    @IBOutlet weak var textField: NSTextField!
    @IBOutlet weak var createButton: NSButton!
    
    override func viewDidLoad()
    {
        super.viewDidLoad()

        self.textField.placeholderString = Strings.TextFieldPlaceholder
        self.textField.toolTip = Strings.TextFieldTooltip
        self.textField.target = self
        self.textField.action = Selector("performRequest:")
        
        self.createButton.toolTip = Strings.ButtonTooltip
    }

    /**
    Performs the URL request that downloads the gitignore that has been
    generated by the backend.
    
    :param: sender The caller of this method
    */
    @IBAction func performRequest(sender: NSButton)
    {
        var urlString = createEndPoint();
        
        if countElements(urlString) > 0 {
            let url = NSURL(string: urlString)
            let request = NSURLRequest(URL: url!)
            
            var session = NSURLSession.sharedSession()
            
            var task = session.dataTaskWithRequest(request, completionHandler: { data, response, error in
                if !(error != nil) {
                    self.saveFile(data, downloadError: error)
                }
            })
            task.resume()
        }
    }
    
    /**
    Shows the NSSavePanel and saves the file to the given folder
    
    :param: gitIgnoreFile The data returned from the backend
    :param: error         The NSError object from the NSURLSession downloadTask
    */
    func saveFile(gitIgnoreFile: NSData?, downloadError: NSError!)
    {
        if let error = downloadError {
            println("An error has occurred. %@", error.localizedDescription)
            
            return
        }
        
        var savePanel = NSSavePanel()
        savePanel.nameFieldStringValue = ".gitignore"
        
        savePanel.beginWithCompletionHandler { (result: Int) -> Void in
            if result == NSFileHandlingPanelOKButton {
                let exportedFileURL = savePanel.URL
                
                gitIgnoreFile?.writeToURL(exportedFileURL!, atomically: true)
            }
        }
    }
    
    /**
    Helper method to create the endpoint from the user inputted string
    
    :returns: The String object representation of the full URL endopint
    */
    func createEndPoint() -> String
    {
        let url = "https://www.gitignore.io/api/"
        
        var returnValue = String();
        
        if countElements(textField.stringValue) > 0 {
            let elementArray = textField.stringValue.componentsSeparatedByCharactersInSet(NSCharacterSet.whitespaceCharacterSet())
            
            var endPoint = String()
            
            for searchTerm in elementArray {
                endPoint = endPoint.stringByAppendingFormat("%@,", searchTerm)
            }
            
            endPoint = endPoint.substringToIndex(advance(endPoint.startIndex, (countElements(endPoint) - 1)))
            
            returnValue = url + endPoint;
        }
        
        return returnValue;
    }
}

